name: GitHub Pages Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Installing Yarn
        run: npm install -g yarn

      - name: Installing dependencies
        run: yarn
      
      - name: Building Pages
        run: yarn build

      - name: Add Commit Hashes
        run: git rev-parse HEAD > ./build/COMMIT

      - name: Patch for React Router
        run: cp ./build/index.html ./build/404.html
        
      - name: Publish into GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          # Git branch where assets will be deployed
          target_branch: "gh-pages"
          # Create incremental commit instead of doing push force
          keep_history: true
          # Build directory to deploy
          build_dir: "./build"
          # The committer name and email address
          committer: "Stella IT <contact@stella-it.com>"
          # The author name and email address
          author: "Stella IT <contact@stella-it.com>"
          # Commit message
          commit_message: "chore: update github pages"
          # Write the given domain name to the CNAME file
          fqdn: "meiling-dev.stella-it.com"
          # Allow Jekyll to build your site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
